def pushGeneratedViews(viewManager, lang=''):
	if lang == '':
		viewManager.PushEffectView(1,lambda source: f"Character is ascendable.","assets/default.webp")
		viewManager.PushEffectView(2,lambda source: f"Character is ascended. After {source.details[0]} rounds; can be on ground.","assets/default.webp")
		viewManager.PushEffectView(3,lambda source: f"Character can be back on the ground.","assets/CHRST/backontheworld.jpg")
		viewManager.PushEffectView(4,lambda source: f"The character is {source.details[0]} % demonized.","assets/Demoneur/thedemon.jpeg")
		viewManager.PushEffectView(5,lambda source: f"a bloody napkin.","assets/images/bloodynapkin.jpg")
		viewManager.PushEffectView(6,lambda source: f"The character is bleeding. (lvl {source.details[0]})","assets/images/bleeding.png")
		viewManager.PushEffectView(7,lambda source: f"The character is carrying {source.details[0]} drops of blood.","assets/images/bleeding.png")
		viewManager.PushEffectView(8,lambda source: f"The character is afraid of something. (lvl {source.details[0]})","assets/images/fear.jpg")
		viewManager.PushEffectView(9,lambda source: f"The character is grabbing something! If moves without grab walking, it will broke.","assets/images/grabbing.png")
		viewManager.PushEffectView(10,lambda source: f"Character PUZZLED! So character is slower and more uneffective than usual.","assets/images/puzzled.png")
		viewManager.PushEventerView(15,lambda source: f"Character gets on the world again, after ascending.","assets/CHRST/backontheworld.jpg")
		viewManager.PushEventerView(16,lambda source: f"I am willing; be cleansed.","assets/CHRST/heal.jpg")
		viewManager.PushEventerView(17,lambda source: f"Takes mud from ground, gives it a shape of a bird. Then blows. (6 use of this eventer is required to blowout)","assets/CHRST/chrstbirds.jpg")
		viewManager.PushEventerView(18,lambda source: f"Make a contract with Rampbist. 1 drop of blood is required.","assets/Demoneur/pentagram.jpg")
		viewManager.PushEventerView(19,lambda source: f"Stab.","assets/Demoneur/demoneurKnife.jpg")
		viewManager.PushEventerView(20,lambda source: f"Claw. Takes a blood. More silent than regular stabbing.","assets/Demoneur/demonclaw.jpg")
		viewManager.PushEventerView(21,lambda source: f"Burn a blood directly to the Rampbist for a quick contract.","assets/Demoneur/rampbistcom.jpg")
		viewManager.PushEventerView(22,lambda source: f"Demon walks.","assets/Demoneur/demonwalk.jpg")
		viewManager.PushEventerView(23,lambda source: f"Lie Down!","assets/images/liedown.webp")
		viewManager.PushEventerView(24,lambda source: f"Get Up!","assets/images/getup.png")
		viewManager.PushEventerView(25,lambda source: f"Grabs a character.","assets/images/grabbing.png")
		viewManager.PushEventerView(26,lambda source: f"Character walks with the thing that the character is grabbing.","assets/images/carryingwalk.png")
		viewManager.PushEventerView(27,lambda source: f"Completely kill your enemy.","assets/images/reaper.png")
		viewManager.PushEventerView(28,lambda source: f"Look.","assets/images/look.png")
		viewManager.PushEventerView(29,lambda source: f"This is a napkin. If theres any on target, takes a liquid.","assets/images/napkin.jpg")
		viewManager.PushEventerView(30,lambda source: f"Punch.","assets/images/punch.jpg")
		viewManager.PushEventerView(31,lambda source: f"Pushes the target forward damaging it (1/2)*STR or (3/2)*STR. Gives the target Puzzled effect.","assets/images/push.png")
		viewManager.PushEventerView(32,lambda source: f"Spends a movement to gain energy.","assets/images/resting.jpg")
		viewManager.PushEventerView(33,lambda source: f"Silent walker for normal characters. In first, will do nothing; in second, will do a less hearable walking.","assets/images/silentwalk.webp")
		viewManager.PushEventerView(34,lambda source: f"More energy consuming, more damaging punch.","assets/images/trickypunch.png")
		viewManager.PushEventerView(35,lambda source: f"Walk!","assets/images/walkingman.jpg")
		viewManager.PushEventerView(36,lambda source: f"Tries to put the character that is grabbing by the character to ground.","assets/images/push.png")
		viewManager.PushEntityView(37,lambda source: f"a bird.","assets/CHRST/bird.png")
		viewManager.PushCharacterView(11,lambda source: f"You know what you see.","assets/CHRST/christ.webp")
		viewManager.PushCharacterView(12,lambda source: f"A silent guy.","assets/Demoneur/demoneur.jpg")
		viewManager.PushCharacterView(13,lambda source: f"Regular human.","assets/images/human.png")
		viewManager.PushCharacterView(14,lambda source: f"A fighter from the streets.","assets/images/fighter.png")
		viewManager.PushWorldEventView("DIVINE_REVELATION", lambda source: f"No explanation entered.", "assets/CHRST/backontheworld.jpg", "assets/sounds/holychoir.mp3")
		viewManager.PushWorldEventView("MVM_ARM_STRETCH", lambda source: f"No explanation entered.", "assets/images/worldevents/armstretch.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_MVM_ARM_STRETCH", lambda source: f"No explanation entered.", "assets/images/worldevents/armstretch.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_HOLYHEAL", lambda source: f"No explanation entered.", "assets/CHRST/heal.jpg", "assets/sounds/holychoir.mp3")
		viewManager.PushWorldEventView("SND_RAMPBIST", lambda source: f"Sound of Rampbist", "assets/Demoneur/thedemon.jpeg", "assets/Demoneur/soundOfRampbist.mp3")
		viewManager.PushWorldEventView("MVM_STAB", lambda source: f"Tries to stab.", "assets/Demoneur/demoneurKnife.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_STABBED", lambda source: f"Something is being stabbed", "assets/images/stabbed.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_STABBED", lambda source: f"Something is being stabbed", "assets/images/stabbed.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_MVM_STAB", lambda source: f"Something tries to stab.", "assets/Demoneur/demoneurKnife.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_CLAW", lambda source: f"Tries to claw something", "assets/Demoneur/demonclaw.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_CLAWED", lambda source: f"Something is being clawed", "assets/Demoneur/demonclaw.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_MVM_CLAW", lambda source: f"Something tries to claw.", "assets/Demoneur/demonclaw.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_NAPKINING", lambda source: f"No explanation entered.", "assets/images/napkin.jpg", "assets/sounds/littlewoosh.mp3")
		viewManager.PushWorldEventView("SND_NAPKINED", lambda source: f"No explanation entered.", "assets/images/napkin.jpg", "assets/sounds/littlefriction.mp3")
		viewManager.PushWorldEventView("VIS_BLEEDING", lambda source: f"Bleeding.", "assets/images/bleeding.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_BREAK_GRABBING", lambda source: f"The grabbing is broken.", "assets/images/worldevents/freedom.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("VIS_BURNING", lambda source: f"BURNING.", "assets/images/burning.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_BURNING", lambda source: f"BURNING.", "assets/images/burning.jpg", "assets/sounds/flame.mp3")
		viewManager.PushWorldEventView("MVM_WHISPER", lambda source: f"Whispering.", "assets/images/whisper.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_WHISPER", lambda source: f"Whispering.", "assets/images/whisper.png", "assets/sounds/whispering.mp3")
		viewManager.PushWorldEventView("MVM_WRITING", lambda source: f"Something is being written.", "assets/images/writing.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_WRITING", lambda source: f"Something is being written.", "assets/images/writing.png", "assets/sounds/writing.mp3")
	if lang == 'tr':
		viewManager.PushEffectView(1,lambda source: f"Karakter yükseltilebilir.","assets/default.webp")
		viewManager.PushEffectView(2,lambda source: f"Karakter yükseltildi. {source.details[0]} tur sonra tekrar yeryüzüne gelebilir.","assets/default.webp")
		viewManager.PushEffectView(3,lambda source: f"Karakter yeryüzüne tekrardan gelebilir.","assets/CHRST/backontheworld.jpg")
		viewManager.PushEffectView(4,lambda source: f"Karakter % {source.details[0]} iblisleştirildi.","assets/Demoneur/thedemon.jpeg")
		viewManager.PushEffectView(5,lambda source: f"kanlı bir peçete.","assets/images/bloodynapkin.jpg")
		viewManager.PushEffectView(6,lambda source: f"Karakter kanıyor. (sv {source.details[0]})","assets/images/bleeding.png")
		viewManager.PushEffectView(7,lambda source: f"Karakter {source.details[0]} damla kan taşıyor.","assets/images/bleeding.png")
		viewManager.PushEffectView(8,lambda source: f"Karakter bir şeyden korkuyor. (sv {source.details[0]})","assets/images/fear.jpg")
		viewManager.PushEffectView(9,lambda source: f"Karakter bir şeyi yakalıyor! Birlikte yürümezse bu bağ kırılır.","assets/images/grabbing.png")
		viewManager.PushEffectView(10,lambda source: f"Karakter ŞAŞIRDI! Yani karakter normale göre daha yavaş ve etkisiz.","assets/images/puzzled.png")
		viewManager.PushEventerView(15,lambda source: f"Karakter yükseltildikten sonra, tekrar dünyaya gelir.","assets/CHRST/backontheworld.jpg")
		viewManager.PushEventerView(16,lambda source: f"O'nun izniyle anadan doğma körleri ve alaca hastalarını iyileştireceğim.","assets/CHRST/heal.jpg")
		viewManager.PushEventerView(17,lambda source: f"Yerden çamur alır, kuş şekli verir ve üfürür. (üfürmek için 6 kullanım gerekir.)","assets/CHRST/chrstbirds.jpg")
		viewManager.PushEventerView(18,lambda source: f"Rampbist ile bir antlaşma yap. 1 damla kan gerekir.","assets/Demoneur/pentagram.jpg")
		viewManager.PushEventerView(19,lambda source: f"Sapla.","assets/Demoneur/demoneurKnife.jpg")
		viewManager.PushEventerView(20,lambda source: f"Pençele. Anında 1 kan alır. Bıçaklamaya göre daha sessiz.","assets/Demoneur/demonclaw.jpg")
		viewManager.PushEventerView(21,lambda source: f"Hızlı bir anlaşma için bir kan damlasını direkt Rampbist için yak.","assets/Demoneur/rampbistcom.jpg")
		viewManager.PushEventerView(22,lambda source: f"Şeytan yürüyor.","assets/Demoneur/demonwalk.jpg")
		viewManager.PushEventerView(23,lambda source: f"Yat Aşağı!","assets/images/liedown.webp")
		viewManager.PushEventerView(24,lambda source: f"Kalk Yukarı!","assets/images/getup.png")
		viewManager.PushEventerView(25,lambda source: f"Bir karakteri yakalar.","assets/images/grabbing.png")
		viewManager.PushEventerView(26,lambda source: f"Karakter, yakaladığı şeyle birlikte yürür.","assets/images/carryingwalk.png")
		viewManager.PushEventerView(27,lambda source: f"Düşmanını tamamen öldür.","assets/images/reaper.png")
		viewManager.PushEventerView(28,lambda source: f"Bakış.","assets/images/look.png")
		viewManager.PushEventerView(29,lambda source: f"Bu bir peçete. Eğer hedefte varsa olan bir sıvıyı alır.","assets/images/napkin.jpg")
		viewManager.PushEventerView(30,lambda source: f"Yumruk.","assets/images/punch.jpg")
		viewManager.PushEventerView(31,lambda source: f"Karaktere (1/2)*STR veya (3/2)*STR hasar vererek iter. İtilen 'şaşırır'.","assets/images/push.png")
		viewManager.PushEventerView(32,lambda source: f"Enerji kazanmak için hareket harcar.","assets/images/resting.jpg")
		viewManager.PushEventerView(33,lambda source: f"Normal karakterler için sessiz yürütücü. İlk başta bir şey yapmaz. İkincide, daha az duyulabilir şekilde yürür.","assets/images/silentwalk.webp")
		viewManager.PushEventerView(34,lambda source: f"Daha fazla enerji tüketen, daha fazla hasar veren yumruk.","assets/images/trickypunch.png")
		viewManager.PushEventerView(35,lambda source: f"Yürü be oğlum!","assets/images/walkingman.jpg")
		viewManager.PushEventerView(36,lambda source: f"Yakaladığı karakteri yere düşürmeye çalışır.","assets/images/push.png")
		viewManager.PushEntityView(37,lambda source: f"bir kuş.","assets/CHRST/bird.png")
		viewManager.PushCharacterView(11,lambda source: f"Ne gördüğünü biliyorsun.","assets/CHRST/christ.webp")
		viewManager.PushCharacterView(12,lambda source: f"Sessiz bir herif.","assets/Demoneur/demoneur.jpg")
		viewManager.PushCharacterView(13,lambda source: f"Sıradan insan.","assets/images/human.png")
		viewManager.PushCharacterView(14,lambda source: f"Sokaklardan bir dövüşçü.","assets/images/fighter.png")
		viewManager.PushWorldEventView("DIVINE_REVELATION", lambda source: f"No explanation entered.", "assets/CHRST/backontheworld.jpg", "assets/sounds/holychoir.mp3")
		viewManager.PushWorldEventView("MVM_ARM_STRETCH", lambda source: f"No explanation entered.", "assets/images/worldevents/armstretch.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_MVM_ARM_STRETCH", lambda source: f"No explanation entered.", "assets/images/worldevents/armstretch.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_HOLYHEAL", lambda source: f"No explanation entered.", "assets/CHRST/heal.jpg", "assets/sounds/holychoir.mp3")
		viewManager.PushWorldEventView("SND_RAMPBIST", lambda source: f"Rampbist'in sesi.", "assets/Demoneur/thedemon.jpeg", "assets/Demoneur/soundOfRampbist.mp3")
		viewManager.PushWorldEventView("MVM_STAB", lambda source: f"Bıçaklamaya çalışıyor.", "assets/Demoneur/demoneurKnife.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_STABBED", lambda source: f"Bişey bıçaklandı.", "assets/images/stabbed.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_STABBED", lambda source: f"Bişey bıçaklandı.", "assets/images/stabbed.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_MVM_STAB", lambda source: f"Bişey bıçaklamaya çalışıyor.", "assets/Demoneur/demoneurKnife.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_CLAW", lambda source: f"Pençelemeye çalışıyor.", "assets/Demoneur/demonclaw.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_CLAWED", lambda source: f"Bişey pençelendi.", "assets/Demoneur/demonclaw.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_MVM_CLAW", lambda source: f"Bişey pençelemeye çalışıyor.", "assets/Demoneur/demonclaw.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("MVM_NAPKINING", lambda source: f"No explanation entered.", "assets/images/napkin.jpg", "assets/sounds/littlewoosh.mp3")
		viewManager.PushWorldEventView("SND_NAPKINED", lambda source: f"No explanation entered.", "assets/images/napkin.jpg", "assets/sounds/littlefriction.mp3")
		viewManager.PushWorldEventView("VIS_BLEEDING", lambda source: f"Kanıyor.", "assets/images/bleeding.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_BREAK_GRABBING", lambda source: f"The grabbing is broken.", "assets/images/worldevents/freedom.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("VIS_BURNING", lambda source: f"YANIYOR.", "assets/images/burning.jpg", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_BURNING", lambda source: f"YANIYOR.", "assets/images/burning.jpg", "assets/sounds/flame.mp3")
		viewManager.PushWorldEventView("MVM_WHISPER", lambda source: f"Fısıldıyor.", "assets/images/whisper.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_WHISPER", lambda source: f"Fısıldıyor.", "assets/images/whisper.png", "assets/sounds/whispering.mp3")
		viewManager.PushWorldEventView("MVM_WRITING", lambda source: f"Bir şey yazılıyor.", "assets/images/writing.png", "assets/sounds/error.wav")
		viewManager.PushWorldEventView("SND_WRITING", lambda source: f"Bir şey yazılıyor.", "assets/images/writing.png", "assets/sounds/writing.mp3")
