classic:
	gcc main.c -I ../TBWGLib/include/ -L ../TBWGLib/libs/ -ltbwg -ltbwgnet -ltbwgessentials -lws2_32 -lm -o ../bin/tbwg_server
debug:
	gcc main.c -I ../TBWGLib/include/ -L ../TBWGLib/libs/ -ltbwgdebug -ltbwgnetdebug -ltbwgessentials -lws2_32 -lm -o ../bin/tbwg_server


