classic:
	gcc -Wno-incompatible-pointer-types main.c -I ../TBWGLib/include/ -L ../TBWGLib/libs -ltbwg -ltbwgnet -ltbwgessentials -lws2_32 -lm -o ../bin/tbwg_server
debug:
	gcc -g -Wno-incompatible-pointer-types main.c -I ../TBWGLib/include/ -L ../TBWGLib/libs -ltbwgdebug -ltbwgnetdebug -ltbwgessentials -lws2_32 -lm -o ../bin/tbwg_server
