#define TGF_FIGHTER_EVENTER_INDICE 10

#define TGF_STREETFIGHTER_PUSH_NAME "TGF_STFGHT_PUSH"
#define TGF_STREETFIGHTER_PUSH (TGF_FIGHTER_EVENTER_INDICE+0)

#define TGF_STREETFIGHTER_GRAB_NAME "TGF_STFGHT_GRAB"
#define TGF_STREETFIGHTER_GRAB (TGF_FIGHTER_EVENTER_INDICE+1)

#define TGF_STREETFIGHTER_GRABWALK_NAME "TGF_STFGHT_GRABWALK"
#define TGF_STREETFIGHTER_GRABWALK (TGF_FIGHTER_EVENTER_INDICE+2)

#define TGF_STREETFIGHTER_SILENTWALK_NAME "TGF_STFGHT_SILENTWALK"
#define TGF_STREETFIGHTER_SILENTWALK (TGF_FIGHTER_EVENTER_INDICE+3)

#define TGF_STREETFIGHTER_TRICKYPUNCH_NAME "TGF_STFGHT_TRICKYPUNCH"
#define TGF_STREETFIGHTER_TRICKYPUNCH (TGF_FIGHTER_EVENTER_INDICE+4)

#define TGF_STREETFIGHTER_GETUP_NAME "TGF_STFGHT_GETUP"
#define TGF_STREETFIGHTER_GETUP (TGF_FIGHTER_EVENTER_INDICE+5)

#define TGF_STREETFIGHTER_GETDOWN_NAME "TGF_STFGHT_GETDWN"
#define TGF_STREETFIGHTER_GETDOWN (TGF_FIGHTER_EVENTER_INDICE+6)

#define TGF_STREETFIGHTER_WRESTLE_NAME "TGF_STFGHT_WRESTLE"
#define TGF_STREETFIGHTER_WRESTLE (TGF_FIGHTER_EVENTER_INDICE+7)

#define TGF_STREETFIGHTER_CHARACTERCODE 2

#include "push.h" // getTgfPush
#include "grab.h" // getTgfGrab
#include "grabwalk.h" // getTgfGrabWalk
#include "silentwalk.h" // getTgfSilentWalk
#include "trickypunch.h" // getTgfTrickyPunch
#include "getup.h" // getTgfGetUp
#include "getdown.h" // getTgfGetDown
#include "wrestle.h" // getTgfWrestle
#include "character.h" // tgfGetStreetFighter